from .base_agent import BaseAgent
import pyperclip
from openai import OpenAI
import os

class ScribeAgent(BaseAgent):
    def __init__(self):
        api_key = os.getenv("OPENAI_API_KEY")
        self.mock_mode = not api_key
        if self.mock_mode:
            self.client = None
        else:
            self.client = OpenAI(api_key=api_key)

    def run(self, temperature: float = 0.3, context: str = None) -> str:
        code_snippet = pyperclip.paste()
        if not code_snippet or len(code_snippet.strip()) == 0:
            return "Clipboard is empty!"

        print(f"Generating docs... (Temp: {temperature})")
        
        if self.mock_mode:
            import time
            time.sleep(1.5)
            docs = "\"\"\"\nThis is a MOCK docstring generated by Synapse.\n\"\"\""
            final_content = f"{docs}\n\n{code_snippet}"
            pyperclip.copy(final_content)
            return "Documentation added to clipboard! (MOCK)"

        try:
            response = self.client.chat.completions.create(
                model="gpt-4o",
                messages=[
                    {"role": "system", "content": "You are an expert technical writer. Write a clear, concise docstring/documentation for the following code. Return ONLY the documentation."},
                    {"role": "user", "content": code_snippet}
                ],
                temperature=temperature
            )
            
            docs = response.choices[0].message.content
            # Optionally append docs to code or just replace clipboard
            # For this demo, let's prepend docs to the code
            final_content = f"{docs}\n\n{code_snippet}"
            pyperclip.copy(final_content)
            return "Documentation added to clipboard!"

        except Exception as e:
            return f"Error generating docs: {str(e)}"
